#server:
#  port: 8080
#  servlet:
#    context-path: /
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
#
#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3307/gdsclocal?characterEncoding=UTF-8&serverTimezone
#    username: root
#    password: 1234
#
#    main:
#      allow-circular-references: true
#
#  jpa:
#    hibernate:
#      ddl-auto: create #create update none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true
#
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
##            client-id: test
##            client-secret: test
#            client-id: 733698268317-t7ast8ineqntnkeh76r8nhvs3di1n3m5.apps.googleusercontent.com
#            client-secret: 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
#            scope:
#              - profile
#              - email
#  profiles:
#    include: oauth
#  session:
#    store-type: jdbc